name: Firebase Continuous Deployment

on:
  push:
    branches: [master]
    paths:
      - public/**

env:
  CI: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - run: cd public && npm install
      - run: cd public && npm run build
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
